export const POST_FAVOURITES_REQUEST = "POST_FAVOURITES_REQUEST";
export const POST_FAVOURITES_SUCCESS = "POST_FAVOURITES_SUCCESS";
export const POST_FAVOURITES_FAILURE = "POST_FAVOURITES_FAILURE";

export const ADD_FAVOURITES_REQUEST = "ADD_FAVOURITES_REQUEST";
export const ADD_FAVOURITES_SUCCESS = "ADD_FAVOURITES_SUCCESS";
export const ADD_FAVOURITES_FAILURE = "ADD_FAVOURITES_FAILURE";
