export const POST_FAVOURITES_SUCCESS = "POST_FAVOURITES_SUCCESS";
export const POST_FAVOURITES_FAILURE = "POST_FAVOURITES_FAILURE";

export const DELETE_FAVOURITES_SUCCESS = "DELETE_FAVOURITES_SUCCESS";
export const DELETE_FAVOURITES_FAILURE = "DELET_FAVOURITES_FAILURE";
