export const FETCH_ITINERARIES_REQUEST = "FETCH_ITINERARIES_REQUEST" 
export const FETCH_ITINERARIES_SUCCESS = "FETCH_ITINERARIES_SUCCESS" 
export const FETCH_ITINERARIES_FAILURE = "FETCH_ITINERARIES_FAILURE"

 
 
    

    
   