export const FETCH_ITINERARIES_REQUEST = "FETCH_ITINERARIES_REQUEST";
export const FETCH_ITINERARIES_SUCCESS = "FETCH_ITINERARIES_SUCCESS";
export const FETCH_ITINERARIES_FAILURE = "FETCH_ITINERARIES_FAILURE";

export const PUT_FAVOURITES_PAGE_REQUEST = "FETCH_FAVOURITES_PAGE_REQUEST";
export const PUT_FAVOURITES_PAGE_SUCCESS = "FETCH_FAVOURITES_PAGE_SUCCESS";
export const ETCH_FAVOURITES_PAGE_FAILURE = "FETCH_FAVOURITES_PAGE_FAILURE";

export const PUT_ITINERARIES_COUNT_REQUEST = "PUT_ITINERARIES_COUNT_REQUEST ";
export const PUT_ITINERARIES_COUNT_SUCCESS = "PUT_ITINERARIES_COUNT_SUCCESS";
export const PUT_ITINERARIES_COUNT_FAILURE = "PUT_ITINERARIES_COUNT_FAILURE";
